@url=http://localhost:3000/api
@json=Content-Type: application/json

###
get {{url}}/users
###
post {{url}}/register
{{json}}

{
  "username": "xxx",
  "password": "123456"
}
###
post {{url}}/login
{{json}}

{
  "username": "xxx",
  "password": "123456"
}